# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fa1f3eaca249fc59d008bb6f8e5dfcb05e788af4ce5269f454123f1b0328d03ea5cb3b710a52d99615d73057376c047aa3325b11b3a99b3e11e73bb0df7b456

test:
  secret_key_base: cf3f1ebf9ff733665711cb92e046878e8b7192d5cf5a92b2fe624e284b9539e5f1257565dc12ab10f98e11ddfc1be0e0967fe79bea11d78a41368da2faba7d9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
